### ISSUE TITLE
terminated job resubmitted 4 times.

### ISSUE THREAD

**Issue by Feiyang472** [deepmodeling/dpdispatcher#113]
It seems these lines of code actually allows a job to fail 5 times instead of three. Is it desired behaviour?

https://github.com/deepmodeling/dpdispatcher/blob/28a5a602396f94062cd3860153d3969444399715/dpdispatcher/submission.py#L515-L526

**Comment by felix5572** [comment]
Not a desired behaviour.. I will fix soon.

**Comment by njzjz** [comment]
I think it will raise error before the 4th resubmit, so a job will only fail 4 times.

**Comment by njzjz** [comment]
We should also give a message to users what to do when it fails.
