### ISSUE TITLE
Output script format may need improvement

### ISSUE THREAD

**Issue by theAfish** [deepmodeling/dpdispatcher#123]
The PBS system is used in the supercomputing resources I use. Meanwhile, the default output script of dpdispatcher (In my case I used dpgen) cannot work in my system which is ascribed to the line "#PBS -l select=1:ncpus=32:ngpus=0".

There are two main problems:
1. The parameter "select=1" is not needed within our supercomputers.
2. This colon-separated writing format on one line may not work for our system.

I have changed the python script for myself but I think there may be others who will encounter the same problem after using it in the future.  So maybe dpdispatcher should write parameters line by line to avoid errors.

And also, the output format could be more flexible. For example, if the input of one parameter is -1, then the program will not output the parameter in the script. Could this be a solution?

**Comment by njzjz** [comment]
What is your PBS version?

**Comment by njzjz** [comment]
Fixed by #376, where one can make all of the input to be customized.

**Comment by theAfish** [comment]
> Fixed by #376, where one can make all of the input to be customized.

I'm sorry, I did not notice the previous comments. But anyway, thank you for the implementation!
