### ISSUE TITLE
Task has no attribute 'load_from_json'

### ISSUE THREAD

**Issue by csu1505110121** [deepmodeling/dpdispatcher#126]
Traceback (most recent call last):
  File "submitted.py", line 6, in <module>
    task0 = Task.load_from_json('json/task.json')
AttributeError: type object 'Task' has no attribute 'load_from_json'

----here is the env I used
# Name                    Version                   Build  Channel
bcrypt                    3.2.0                    pypi_0    pypi
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
certifi                   2021.5.30                pypi_0    pypi
cffi                      1.14.6                   pypi_0    pypi
charset-normalizer        2.0.4                    pypi_0    pypi
cryptography              3.4.7                    pypi_0    pypi
dargs                     0.2.6                    pypi_0    pypi
dpdispatcher              0.3.39                   pypi_0    pypi
idna                      3.2                      pypi_0    pypi
libcxx                    12.0.1               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
openssl                   1.1.1k               h3422bc3_1    conda-forge
paramiko                  2.7.2                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pycparser                 2.20                     pypi_0    pypi
pynacl                    1.4.0                    pypi_0    pypi
python                    3.8.10          hf9733c0_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
setuptools                57.4.0           py38h10201cd_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               h72a2b83_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
urllib3                   1.26.6                   pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge

**Comment by njzjz** [comment]
How did you import `Task`? Did you override it?

**Comment by csu1505110121** [comment]
Below is my code
---
  1 from dpdispatcher import Machine, Resources, Task, Submission
  2
  3 machine = Machine.load_from_json('json/machine.json')
  4 resources = Resources.load_from_json('json/resources.json')
  5
  6 task0 = Task.load_from_json('json/task.json')

**Comment by njzjz** [comment]
Ok, I can reproduce.

**Comment by njzjz** [comment]
I can confirm there's no such method in this class. The document is wrong, or we forgot to add this method...

**Comment by csu1505110121** [comment]
OK, hope to see the latest doc soon!
