### ISSUE TITLE
why jobs have started running in diffrent folder when I run two same submission?

### ISSUE THREAD

**Issue by LiuGaoyong** [deepmodeling/dpdispatcher#133]
Hi , guys.

I got a problem: Firstly, I run a job submission, then I stop it ( use Ctrl+C ). Secondly, I restart this same job, but the dpdispatcher cannot restart this jobs submission from last folder. **It run a new calculation from a new folder.**

Why cause this and how to fix it?

Thanks for any help.

**Comment by njzjz** [comment]
Are you sure you didn't change the parameters or upgrade?

**Comment by felix5572** [comment]
Could you please check if the json file which records the submission information has changed?

**Comment by LiuGaoyong** [comment]
> Are you sure you didn't change the parameters or upgrade?

Yes, I confirm this.  I just do **run -> Ctrl+c -> run again**.

**Comment by LiuGaoyong** [comment]
> Could you please check if the json file which records the submission information has changed?

If you mean the "UUID.json" in the work folder, I think it may be the reason of this problem. The "UUID.json" appears in the remote work folder, but not in the local work folder.

I will make further exploration with this problem.

**Comment by njzjz** [comment]
@LiuGaoyong You may check if `UUID.json` in old and new directories has any different content.

**Comment by LiuGaoyong** [comment]
After some time, I find this problem is associated with the time of (1) in "run ---(1)---> Ctrl+c ---(2)---> run again".  This problem appear only when this time is very short. 

This  problem may be caused by the files-uploading or something needing write on remote cannot be executed on remote machine in such short time.

23333333
