### ISSUE TITLE
Compatibility of PBS (Torque 4.2.7)

### ISSUE THREAD

**Issue by cherushui** [deepmodeling/dpdispatcher#142]
My cluster is using an older version of PBS management. When using dpgen-0.9.0, the PBS submit is normal. When change to dpgen-0.10.3, with dpdispatcher 0.3.43, two problems occur:

**1. the submit PBS tasks are always waiting in line.**
![image](https://user-images.githubusercontent.com/20479263/138383648-195506e8-ef82-4832-baa9-70fd435b9b06.png)

I check the submit script [[PBS script.zip](https://github.com/deepmodeling/dpdispatcher/files/7393952/PBS.script.zip)], found the PBS parameters as  "#PBS -l select=1:ncpus=4:ngpus=0", this format is not compatible with my PBS management. 
While In the older version dpgen/dispatcher/PBS.py (https://github.com/deepmodeling/dpgen/blob/master/dpgen/dispatcher/PBS.py) , using the format of "'#PBS -l nodes=%d:ppn=%d\n'" is OK.
I've checked the newly updated support in Torque(https://github.com/deepmodeling/dpdispatcher/blob/master/dpdispatcher/pbs.py) and not found the change in the PBS script head format.

**2. qstat -x error**
status_word = status_line.split ()[-2]        
IndexError: list index out of range

, which i believe the similar question of pull#86 https://github.com/deepmodeling/dpdispatcher/pull/86

**Comment by njzjz** [comment]
If you are using Torque, please set `batch_type` to `Torque`.

**Comment by njzjz** [comment]
Your Torque version is too old to support the new format. I think it's possible to check the Torque version on the fly, but since Torch is not open-source, we cannot help for it.

**Comment by LavendaRaphael** [comment]
I find the format is not changed even in newest version Torque 6.1.3 (2021.02)
<https://support.adaptivecomputing.com/wp-content/uploads/2021/02/torque/torque.htm#topics/torque/2-jobs/requestingRes.htm>
