### ISSUE TITLE
ERROR: No matching distribution found for setuptools_scm

### ISSUE THREAD

**Issue by Aunity** [deepmodeling/dpdispatcher#153]
I download dpdispatcher version 0.3.46 and run python setup.py install. Some errors happened.

$# python setup.py install

WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
**ERROR: Could not find a version that satisfies the requirement setuptools_scm
ERROR: No matching distribution found for setuptools_scm**

Finally, I solved this problem by commented line 27 in the steup.py file.
```
 26     use_scm_version={'write_to': 'dpdispatcher/_version.py'},
 27     #setup_requires=['setuptools_scm'],

**Comment by felix5572** [comment]
just try `pip install setuptools_scm`
or  use `pip install setuptools_scm -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by njzjz** [comment]
Please use `pip install .` instead  of unsupported `python setup.py install`.
