### ISSUE TITLE
new PRs in DP-GEN

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/dpdispatcher#16]
New PRs related to dpdispatcher in DP-GEN:
- [x] deepmodeling/dpgen#380 -> #21
- [x] deepmodeling/dpgen#381 -> #24
- [x] deepmodeling/dpgen#382 -> #22
- [x] deepmodeling/dpgen#383
- [x] deepmodeling/dpgen#387 -> #25
- [x] deepmodeling/dpgen#396 -> #23

**Comment by felix5572** [comment]
I will implement it in this repo soon (and add unittests)
