### ISSUE TITLE
Errors in document

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#173]
## 1
According to `submission.py`, `if_cuda_multi_devices` default is `False`, but in <https://docs.deepmodeling.org/projects/dpdispatcher/en/latest/resources.html> it is `True`
```py
default_strategy = dict(if_cuda_multi_devices=False, ratio_unfinished=0.0)
```
## 2
There is a typo error `resources=reasources,` in <https://docs.deepmodeling.org/projects/dpdispatcher/en/latest/getting-started.html> example code block

**Comment by njzjz** [comment]
Contribution is welcome.
