### ISSUE TITLE
Extra temp hash empty dir appears in `SSHContext` remote

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#177]
I found that when I use `SSHContext`, after running `dpdispatcher`, 2 hash directories appear in the remote directory:
- One is empty.
- The other is the working directory,

I found out that the problem is
- When dpdispatcher initializes a `Submission` instance, it creates the first useless directory
https://github.com/deepmodeling/dpdispatcher/blob/793a7d50e5594f5aa309b76b314e89fdaf7ad107/dpdispatcher/submission.py#L56
https://github.com/deepmodeling/dpdispatcher/blob/793a7d50e5594f5aa309b76b314e89fdaf7ad107/dpdispatcher/ssh_context.py#L289
- Then create the real working directory after `Submission.run_submission`
https://github.com/deepmodeling/dpdispatcher/blob/793a7d50e5594f5aa309b76b314e89fdaf7ad107/dpdispatcher/submission.py#L169
https://github.com/deepmodeling/dpdispatcher/blob/793a7d50e5594f5aa309b76b314e89fdaf7ad107/dpdispatcher/submission.py#L330

**Comment by njzjz** [comment]
We may not need to create a directory at `bind_machine`.

**Comment by njzjz** [comment]
Fixed by #261.

**Comment by njzjz** [comment]
Fixed in #346.
