### ISSUE TITLE
Risk of leaking password

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#179]
I noticed that dpdispatcher creates a `<submission_hash>.json` with permissions `-rw-r--r--` in the remote directory, which contains the password information in `remote_profile`. I think there is a risk of leaking the password.

**Comment by njzjz** [comment]
We do not recommend using the `password` parameter. A [SSH key](https://www.ssh.com/ssh/key/) should be used instead.
