### ISSUE TITLE
Symlink directories are ignored in subdirectories of `forward_common_files` in SSHContext

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#184]
Local directory tree like this
````
.
├── testdir
│ └── testlink-> ../../testsubdir
````
If I set `forward_common_files=['testdir']`, then in the remote directory, there will be no testdir and its subdirectories.
I think the problem is
https://github.com/deepmodeling/dpdispatcher/blob/9438565a7651a7ada0f68d48e77ab1e0450d9c5e/dpdispatcher/ssh_context.py#L313
This might fix it:
````py
         for root, dirs, files in os.walk(file_name, topdown=False, followlinks=True) :
````

**Comment by njzjz** [comment]
Could you submit a pull request?
