### ISSUE TITLE
Wrong job_id in LSF 10.1.0.0

### ISSUE THREAD

**Issue by LavendaRaphael** [deepmodeling/dpdispatcher#200]
I am using dpdispatcher in a LSF system, (IBM Spectrum LSF 10.1.0.0 build 520099), but it can't get right jobid.
When I `print(subret)`, it return
```
['Submiting job\n', 'Job <2861772> is submitted to queue <snode>.\n']
```
https://github.com/deepmodeling/dpdispatcher/blob/6680b499d34c07a810c5263aaaa09c15535102dd/dpdispatcher/lsf.py#L70-L74

**Comment by njzjz** [comment]
Is it a breaking change of LSF? Old versions of LSF should work. Is there a way to get the version?

**Comment by LavendaRaphael** [comment]
> Is it a breaking change of LSF? Old versions of LSF should work. Is there a way to get the current version?
Well, I found that it was a problem with the cluster I was using. The administrator changed the default behavior of the bsub command. So this is not an official change.
