### ISSUE TITLE
paramiko.ssh_exception.SSHException: Server connection dropped

### ISSUE THREAD

**Issue by wankiwi** [deepmodeling/dpdispatcher#248]
I recently encountered a problem when using dpgen to perform the model deviation. When paramiko downloads a large file, it will report the following error
`paramiko.ssh_exception.SSHException: Server connection dropped`
The error occurs when downloading the tar file of model_devi (123 Gb), which is consistent with the situation described in this article https://zhuanlan.zhihu.com/p/102372919.
At present, the process of dpgen is to download the trajectory to the local and then obtain the candidate structures through analysis. If it can be changed to analyze the trajectory on the remote server, get the candidate structure and then download it locally, it can avoid downloading large trajectory files, greatly speeds up the process, and avoid the above errors.
I hope the developers can consider my suggestion, thank you very much.

**Comment by njzjz** [comment]
Paramiko is confirmed to be unstable. #170 has provided `rsync` backend which should be more stable.

**Comment by wankiwi** [comment]
How to switch to rsync backend in dpgen? Is there any suggestions for taking too long to download data from remote and decompress locally in model_devi step?
Thanks a lot.

**Comment by njzjz** [comment]
This should be automatic. Have you installed rsync?

**Comment by njzjz** [comment]
Do you use any of custom password, port, key_filename, or passphrase? These are not supposed yet.

**Comment by wankiwi** [comment]
> Do you use any of custom password, port, key_filename, or passphrase? These are not supposed yet.

Thanks, I did use the custom key_file, hope the new verison to support it.
BTW, is it possible that the requirements I describe will be implemented in a future version?

**Comment by njzjz** [comment]
For DP-GEN features please submit a separate issue to DP-GEN for better tracking.

**Comment by wankiwi** [comment]
> For DP-GEN features please submit a separate issue to DP-GEN for better tracking.

OK.
