### ISSUE TITLE
update class introduction and docs for main class 

### ISSUE THREAD

**Issue by felix5572** [deepmodeling/dpdispatcher#31]
update docs for class `Resources`  `Submission` `Task`  `Job`  `BaseContext`

reference:
1. use deepmodeling/dargs

2. example: https://github.com/deepmodeling/deepmd-kit/blob/b3cfe45088135c144b358750119781fa03e577af/deepmd/infer/deep_pot.py#L17-L32

**Comment by njzjz** [comment]
Current https://github.com/deepmodeling/dpdispatcher/blob/master/doc/api.rst is out of date.

**Comment by njzjz** [comment]
We don't have the parameter document for `Task`, right?

**Comment by felix5572** [comment]
added in pr #55  @njzjz
