### ISSUE TITLE
Hope to support the setting of dcu in slurm

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/dpdispatcher#422]
The sugon platform support to use dcu, and can set the number of dcu by `#SBATCH --gres=dcu:4`, which means use 4 dcu.

**Comment by njzjz** [comment]
Setting `custom_gpu_line` to `#SBATCH --gres=dcu:4` should work. For details, see documentation.

**Comment by pxlxingliang** [comment]
> Setting `custom_gpu_line` to `#SBATCH --gres=dcu:4` should work. For details, see documentation.

It is not work in dflow DispatcherExecutor that set custom_gpu_line in resource_dict, but set `#SBATCH --gres=dcu:4`  in `custom_flags` in resource_dict is worked.

**Comment by njzjz** [comment]
@zjgemi any idea?
