### ISSUE TITLE
{question] anyway to set the number of resubmission fail jobs?

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/dpdispatcher#502]
Dear Devs, 

I wonder there is anyway to set the number of resubmission on fail jobs? (or changing the default value}

Thanks

**Comment by njzjz** [comment]
For example,
```py
machine.retry_count = 10
```

**Comment by thangckt** [comment]
hi @njzjz 
Can you show me where to set `machine.retry_count`?

I try in machine dict with 
```
machine: {retry_count: 0} 
```
But is does not take effct.
