### ISSUE TITLE
`check_status()` always return `JobStatus.unknown` unless `qstat -x` not return `0`

### ISSUE THREAD

**Issue by saltball** [deepmodeling/dpdispatcher#84]
# Some environment info:
`dpdispatcher`: updated with branch `master`
`python`: 3.8
"`pbs`": torque-6.1
# Description
dpdispatcher works well on `Machine` with batch_type = `slurm`, `shell` but not `PBS`.
I think maybe `qstat -x` in **Line 53** has different behavior on my nodes and yours.
https://github.com/deepmodeling/dpdispatcher/blob/60f5c90ef3b57dbbb270aeea8565bde74a53fdbd/dpdispatcher/pbs.py#L48-L78
1. If one job has been finished moments ago, and `qstat` return with nothing but return to stderr. 
Code in `check_status()` will go into **Line 56**, and return JobStatus.finished or JobStatus.terminated.
And truth is I can get correct result (files downloaded, python exit with 0) after a while.
2. But the script will raise a RuntimeError 
```
RuntimeError: job_state for job ...<json info of the job, not important>... is unknown
```
# Locate the problem
`qstat -x` seems to return a somewhat `XML` format (maybe) like: (on shell, not from script)
```xml
<?xml version="1.0"?>
<Data></Data>
```
on my nodes.

I'm not sure whether I did anything wrong, or "`pbs`" not works the same way as yours. Perhaps @felix5572 knows this well.
Maybe you are using `PBS PRO` but I'm using `Torque`.

By the way, I can also got `job_state` from my `qstat -x` return with label `<job_state>` but not simple `.split()[-2]`

```xml
<?xml version="1.0"?>
<Data>
<Job>
....
<job_state>C</job_state>
....
</Job>
</Data>
```

**Comment by felix5572** [comment]
It seems that `qstat -x` returns a xml file..  But In our systems, it returns just a string.

**Comment by njzjz** [comment]
What's your PBS version? I guess there is a breaking change here in the new version..

**Comment by saltball** [comment]
> What's your PBS version? I guess there is a breaking change here in the new version..

@njzjz My `PBS` is acctually torque(6.1).
By the way, I can't find any information about `qstat -x` return string. Maybe you can offer some docstring describing this.
Also, `qstat -x` on my system seems equal to `qstat -xml`. I can use `qstat -l` without any error now.

**Comment by njzjz** [comment]
Is it https://en.wikipedia.org/wiki/TORQUE? The page said it's based on the original PBS but different from https://github.com/openpbs/openpbs. And it's not open-source.
I suggest to add a new `Machine` to dpdispatcher as it's a different software.

**Comment by saltball** [comment]
@njzjz Yes, I think they are different even though they share some commands. And I agree a new `Machine` is necessary. For now, maybe a subclass could work well, by a line change to `qstat -l`. Please check #86.
And I suggest to add more docs to notice other users.

**Comment by saltball** [comment]
I think #86 can solve this.
